<?php
/**
 * GePanel
 * 
 * Шаблон ошибки 404 (Not Found).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 RosGear
 * @package Theme
 * @subpackage Green
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка 404 (Не найдено)</title>
    <link type="image/png" href="<?= Ge::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Ge::getAlias('@theme::/assets/css/error.min.css') ?>" />
</head>

<body class="g-error g-error_404">
    <div class="g-error__wrapper">
        <h1 class="g-error__header">Ошибка 404 (Не найдено)</h1>
        <div class="g-error__text">
            <p>Вы пытаетесь получить доступ к странице, которая возможно была удалена.</p>
            <ol>
                <li>Проверьте корректность вводимого вами адреса и/или скорректируйте его.</li>
                <li>Очистите кэш вашего браузера и попробуйте обратиться к странице вновь.</li>
                <li>Перейдите на главную страницу сайта и попробуйте найти нужную информацию, переходя по ссылкам.</li>
                <li>Поищите страницу в поисковых системах — возможно страница была опубликована по новому адресу.</li>
            </ol>
        </div>
    </div>
</body>

</html>