<?php
/**
 * GePanel
 * 
 * Шаблон ошибки подключения к базе данных.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 RosGear
 * @package Theme
 * @subpackage Green
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка подключения к базе данных</title>
    <link type="image/png" href="<?= Ge::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Ge::getAlias('@theme::/assets/css/error.min.css') ?>" />
</head>

<body class="g-error g-error_db">
    <div class="g-error__wrapper">
        <div class="g-error__title"><?= Ge::$app->version->nameToHtml() ?><span class="copyright">&copy;</span></div>
        <div class="g-error__text">
            <div class="g-error__icon g-error__icon-db"><?= $exception->getDispatch() ?></div>
        </div>
    </div>
</body>

</html>