<?php
/**
 * GePanel
 * 
 * Шаблон ошибки 503 (Service Temporary Unavailability).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 RosGear
 * @package Theme
 * @subpackage Green
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error 503 (Site is temporarily unavailable)</title>
    <link type="image/png" href="<?= Ge::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Ge::getAlias('@theme::/assets/css/error.min.css') ?>" />
</head>

<body class="g-error g-error_403">
    <div class="g-error__wrapper">
        <h1 class="g-error__header">Error 503 (Site is temporarily unavailable)</h1>
        <div class="g-error__text">
            <p>We apologize. The site is temporarily unavailable and is under maintenance.</p>
        </div>
    </div>
</body>

</html>